GET http://localhost:8080/notes
###

GET http://localhost:8080/notes/2
###

POST http://localhost:8080/notes
Content-Type: application/json

{
    "title": "Go to the gym",
    "content":"Do not forget to visit gym today."
}

###
//Change Title
PUT http://localhost:8080/notes/1
Content-Type: application/json

{
"title":"Go to the school"
}

###
//Change Content
PUT http://localhost:8080/notes/1
Content-Type: application/json

{
  "content":"Knowledge is very important"
}