DELETE
from notes;

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name CHARACTER VARYING(30) NOT NULL,
    last_name  CHARACTER VARYING(30) NOT NULL,
    is_active  BOOLEAN               NOT NULL default TRUE
);

ALTER TABLE notes
    ADD COLUMN user_id BIGINT NOT NULL REFERENCES users (id);




