CREATE TABLE auth_credentials
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) UNIQUE NOT NULL,
    user_id       BIGINT UNIQUE       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    password_hash VARCHAR(255)        NOT NULL,
    created_at    timestamptz         NOT NULL
);




