CREATE TABLE notes
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title CHARACTER VARYING(30),
    content VARCHAR,
    created_at DATE NOT NULL,
    updated_at DATE,
    is_archived BOOLEAN
);